name: Proxy Analyzer

on:
  workflow_dispatch:
    inputs:
      subscribe_url:
        description: '输入订阅链接'
        required: true

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 安装依赖
        run: |
          sudo apt-get update
          sudo apt-get install -y \
              coreutils \
              jq \
              curl \
              bc \
              netcat-openbsd

      - name: 运行解析脚本
        env:
          SUB_URL: ${{ github.event.inputs.subscribe_url }}
        run: |
          chmod +x ./scripts/parse_proxies.sh
          ./scripts/parse_proxies.sh "$SUB_URL"